import networkx as nx
import matplotlib.pyplot as plt
import EoN
import pandas as pd
import numpy as np
from collections import defaultdict
import sys

# set the parameters for the simulation
gamma = 0.2
tau = 0.5

# control if the user has provided the arguments of the command line, that is the graph folder and the time series file generated by the MASFENON simulation
if len(sys.argv) < 2:
    print('Usage: python generalEoFparameterFitting.py <graph_folder> <time_series_file>') # TODO expand with another time series file for the SIRS simulation
    sys.exit(1)

# read the graph folder from the command line
graphFolder = sys.argv[1]


# get the network from one of the generated files that contains the edge data (Start, End, Weight), first line is the header
graphEdgesFile = '/edge_data.tsv'
G = nx.Graph()
with open(graphEdgesFile, 'r') as f:
    # skip the header
    f.readline()
    for line in f:
        start, end, weight = line.strip().split('\t')
        G.add_edge(start, end, weight=float(weight))

# read the initial condition of every node from a file
# the file should have the following format:
# node_name  condition(Susceptible, Infected)
initialConditionFile = '/home/josura/Projects/ccc/c2c-sepia/scripts/R/epidemics/significanceAnalysys/preferentialAttachment/10000nodes/1/node_conditions.tsv'
initialConditions = {}
with open(initialConditionFile, 'r') as f:
    for line in f:
        node, condition = line.strip().split('\t')
        initialConditions[node] = condition

# get the initial infecteds
initial_infecteds = []
for node in G.nodes():
    if initialConditions[node] == 'Infectious':
        initial_infecteds.append(node)


# run the SIS simulation in the graphs
t_sis, S_sis, I_sis = EoN.fast_SIS(G, tau, gamma, initial_infecteds=initial_infecteds, tmax=100)

# run the SIR simulation in the graph
t_sir, S_sir, I_sir, R_sir = EoN.fast_SIR(G, tau, gamma, initial_infecteds=initial_infecteds, tmax=100)

# SIRS simulation setup

H = nx.DiGraph()  #DiGraph showing possible transitions that don't require an interaction
H.add_edge('I', 'R', rate = 0.2)   # recovery rate
H.add_edge('R', 'S', rate = 0.1)   # immunity loss rate

J = nx.DiGraph()    #DiGraph showing transition that does require an interaction.
J.add_edge(('I', 'S'), ('I', 'I'), rate = 0.5)  #IS->II

IC = defaultdict(lambda: 'S')
for node in initial_infecteds:
    IC[node] = 'I'

return_statuses = ('S', 'I', 'R')

t_sirs, S_sirs, I_sirs, R_sirs = EoN.Gillespie_simple_contagion(G, H, J, IC, return_statuses, tmax = 100)


# read timeseries from the file
timeSeriesParameterSIS = '/home/josura/Projects/ccc/c2c-sepia/outputsTimeSeries/parameterSetting/preferentialAttachment/dissipationScaleFactor0.8_propagationScaleFactor64.0/allFiles/fullGraph_output.tsv'

timeSeries_dataframeSIS = pd.read_csv(timeSeriesParameterSIS, sep='\t')
thresholded_timeseriesSIS = timeSeries_dataframeSIS.copy()

thresholded_timeseriesSIS.iloc[:, 1:] = np.where(thresholded_timeseriesSIS.iloc[:, 1:] > 0.5, 1, 0)
# sort the rows by the time column
thresholded_timeseriesSIS = thresholded_timeseriesSIS.sort_values(by='time')

# get the number of infecteds at each time
infectedsSIS = thresholded_timeseriesSIS.iloc[:, 1:].sum(axis=1)

# plot the number of infecteds from the EoN simulation and the thresholded timeseries as line plots
plt.plot(t_sis, I_sis, label='EoN SIS simulation')
plt.plot(t_sir, I_sir, label='EoN SIR simulation')
plt.plot(t_sirs, I_sirs, label='EoN SIRS simulation')
plt.plot(thresholded_timeseriesSIS['time'], infectedsSIS, label='MASFENON simulation')
plt.xlabel('Time')
plt.ylabel('Number of infecteds')
plt.legend()
plt.title('Number of infecteds in the preferential attachment network of 10000 nodes')

plt.show()
