version: '3.8'

services:
  sepia-worker:
    restart: always
    build: .
    container_name: c2c-sepia-container
    environment:
      - SEPIA_WORKER_QUEUE=sepia
      #add env variables

    volumes:
      - .:/opt/sepia


volumes:
  c2c-sepia-data: