---
title: "creating inputs for fluxes"
---

```{r}
library(CellChat)
library(Seurat)
library(readr)
library(Matrix)
#library for transpose function
library(data.table)
```

```{r}
# information about the graph that will be built from the metabolic network
# module info has the following format:
# M_id	M_name	C_in	C_in_name	C_out	C_out_name	Supermodule_id
moduleInfoLocation <- "/home/josura/Projects/ccc/fluxes/scFEA/data/scFEA.M171.mouse.moduleinfo.csv"
# incidence matrix has the following format:
# rows are the metabolites(70 metabolites), columns are the modules(171 modules)
incidenceMatrixLocation <- "/home/josura/Projects/ccc/fluxes/scFEA/data/cmMat_complete_mouse_c70_m168.csv"
# module to gene influence has the following format:
# first column is the module id, everything after is the list of genes that are influenced by the module
moduleToGeneInfluenceLocation <- "/home/josura/Projects/ccc/fluxes/scFEA/data/module_gene_complete_mouse_m168.csv"
# fluxes file generated from scFEA
metabolitesFluxesLocation <- "/home/josura/Projects/ccc/fluxes/scFEA/output/scRNA_6h_metabolites_module168_cell1037_20241014-125629.csv"
modulesFluxesLocation <- "/home/josura/Projects/ccc/fluxes/scFEA/output/scRNA_6h_module168_cell1037_20241014-125629.csv"
```
# read the network information
```{r}
moduleInfo <- read_csv(moduleInfoLocation)
incidenceMatrix <- read_csv(incidenceMatrixLocation)
moduleToGeneInfluence <- read_csv(moduleToGeneInfluenceLocation)
```

# read the fluxes
```{r}
metabolitesFluxes <- read_csv(metabolitesFluxesLocation)
modulesFluxes <- read_csv(modulesFluxesLocation)
```

# transform the data
```{r}
# convert the module to gene influence to a map of moduleId -> <geneList>
moduleIDS <- moduleToGeneInfluence[,1]
moduleMapToGeneList <- list()
for (i in 1:length(moduleIDS)){
  moduleMapToGeneList[[moduleIDS[i]]] <- moduleToGeneInfluence[i,-1] %>% unlist %>% na.omit
}
```

```{r}

